# .github/workflows/update.yml
name: Atualizar Resultados Diariamente

on:
  schedule:
    - cron: '0 11 * * *'  # 08:00 BRT = 11:00 UTC
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install requests

      - name: Run update script
        run: python update_results.py

      - name: Commit and push if changed
        run: |
          git config user.name "Rastreador Automático"
          git config user.email "bot@rastreador.local"
          git add data.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Atualizado automaticamente: $(date)"
          git push origin main
