name: Atualizar data.json (Diariamente)

on:
  schedule:
    - cron: '0 6 * * *'  # Todo dia às 06:00 (Brasília)
  workflow_dispatch:

jobs:
  update-
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Gerar data.json com os jogos de hoje
        run: |
          echo '{
            "2025": {
              "71": {
                "Bahia": {
                  "results": ["V", "V"],
                  "next_opponent": "Santos",
                  "opponent_table": "Z4",
                  "form_opponent": "D,D",
                  "position": 5,
                  "points": 33,
                  "avg_goals": 1.7,
                  "avg_corners": 5.2,
                  "home_away": "Casa",
                  "injuries": "Nenhum",
                  "new_coach": false,
                  "last_5_summary": "3V,1E,1D",
                  "match_date": "24/08/2025",
                  "match_time": "18:30"
                }
              },
              "39": {
                "Manchester City": {
                  "results": ["V", "V"],
                  "next_opponent": "West Ham",
                  "opponent_table": "Meio da tabela",
                  "form_opponent": "E,D",
                  "position": 1,
                  "points": 47,
                  "avg_goals": 2.5,
                  "avg_corners": 7.0,
                  "home_away": "Casa",
                  "injuries": "Nenhum",
                  "new_coach": false,
                  "last_5_summary": "5V",
                  "match_date": "24/08/2025",
                  "match_time": "17:30"
                }
              },
              "61": {
                "PSG": {
                  "results": ["V", "V"],
                  "next_opponent": "Marseille",
                  "opponent_table": "Meio da tabela",
                  "form_opponent": "E,D",
                  "position": 1,
                  "points": 22,
                  "avg_goals": 2.5,
                  "avg_corners": 6.2,
                  "home_away": "Casa",
                  "injuries": "Nenhum",
                  "new_coach": false,
                  "last_5_summary": "5V",
                  "match_date": "24/08/2025",
                  "match_time": "21:00"
                }
              }
            }
          }' > data.json

      - name: Commit e Push
        run: |
          git config user.name "trederfrancisco-jpg"
          git config user.email "seu-email@exemplo.com"
          git add data.json
          git commit -m "📅 Atualizado automaticamente: data.json" || echo "Sem alterações"
          git push
